server:
  port: 8082
  servlet:
   context-path: /demo

application:
  name: @artifactId@
  version: @version@
developer:
  name: ender
  website: http://ender.com
  qq: 1818182331
  phone-number: 432423523